/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminMenuButton: typeof import('./src/components/adminMenuButton.vue')['default']
    ButtonsCategories: typeof import('./src/components/buttonsCategories.vue')['default']
    CardCategories: typeof import('./src/components/cardCategories.vue')['default']
    CartButton: typeof import('./src/components/cartButton.vue')['default']
    CategoriesList: typeof import('./src/components/categoriesList.vue')['default']
    FormsRegister: typeof import('./src/components/formsRegister.vue')['default']
    HeaderComp: typeof import('./src/components/headerComp.vue')['default']
    ModalCreate: typeof import('./src/components/modalCreate.vue')['default']
    ModalCreateProduct: typeof import('./src/components/modalCreateProduct.vue')['default']
    ModalDelete: typeof import('./src/components/modalDelete.vue')['default']
    ModalDeleteProduct: typeof import('./src/components/modalDeleteProduct.vue')['default']
    ModalEdit: typeof import('./src/components/modalEdit.vue')['default']
    ModalEditProduct: typeof import('./src/components/modalEditProduct.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
