/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ButtonsCategories: typeof import('./src/components/buttonsCategories.vue')['default']
    CardCategories: typeof import('./src/components/cardCategories.vue')['default']
    FormsRegister: typeof import('./src/components/formsRegister.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/pages/Home-page.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LoginPage: typeof import('./src/pages/Login-page.vue')['default']
    ModalCriar: typeof import('./src/components/modalCriar.vue')['default']
    ModalEditar: typeof import('./src/components/modalEditar.vue')['default']
    ModalExcluir: typeof import('./src/components/modalExcluir.vue')['default']
    NavigationBar: typeof import('./src/components/navigation-bar.vue')['default']
    RegisterPage: typeof import('./src/pages/Register-page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
