/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Anal-page': RouteRecordInfo<'/Anal-page', '/Anal-page', Record<never, never>, Record<never, never>>,
    '/Home-page': RouteRecordInfo<'/Home-page', '/Home-page', Record<never, never>, Record<never, never>>,
    '/Login-page': RouteRecordInfo<'/Login-page', '/Login-page', Record<never, never>, Record<never, never>>,
    '/Register-page': RouteRecordInfo<'/Register-page', '/Register-page', Record<never, never>, Record<never, never>>,
  }
}
